Add optional audio bus support
bbbscarter/event-audio-godot pull request #1
Opened 2024-11-02 15:57 UTC by zegenie

This PR adds support for specifying an audio bus per sound event. The audio bus defaults to the `Master` bus, but lets you override this per audio event.

In addition, expanded the `play_2d()` and `play_3d()` methods to allow overriding or specifying an audio bus direction when playing the event.

2024-11-02 15:58 UTC, zegenie commented
I see there are some whitespace differences, this must have come from the godot import :(

2024-11-04 10:40 UTC, bbbscarter requested changes
The basic change looks good, and knocks one of the things off my TODO list. Thanks!

As you suggest, the whitespace is a problem; I presume tab width is set to 8 in Godot? Would you be able to fix that up to clean up the diff?

Thanks!

Simon

2024-11-04 12:51 UTC, zegenie commented
Fixed whitespace issues and updated the PR.

2024-11-04 14:32 UTC, bbbscarter commented
LGTM - thanks!

2024-11-04 14:32 UTC, merged